apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: grade-submission
spec:
  selector:
    # app.kubernetes.io/name: grade-submission
    app.kubernetes.io/instance: mongodb
    # app.kubernetes.io/component: database
  ports:
  - port: 27017
    targetPort: 27017
